server:
  port: 9000

#日志
logging:
  level:
    root: WARN

#配置激活的profile，配合在Bean上标注的@Profile("production")注解可以激活指定的Bean
#配合application-{profile}.properties格式的属性文件，可以激活指定的属性配置。
#配合使用---分割的yml配置文件。以及其中各段指定的spring.profiles: development属性，也可以激活特定的属性配置。

spring:
  profiles:
    active: production
  #db设置
  datasource:
    url: jdbc:mysql://localhost:3306/doc_manager?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool-size: 30
  devtools:
    restart:
      enabled: true  #设置开启热部署
#百度云OCR设置
ocr:
  appid: 16963748
  appkey: bSEovX4T3o3d0Lvt49i89Eyn
  secretkey: GAX6iuR0YQ86nKVSoAG5tV7sILy5bc1M

#Es索引设置
es:
  library: library
  host: localhost
  port: 9200
  index:
    shards: 2
    replicas: 3

